Testsuite: com.sample.ExceptionProcessTest
Tests run: 1, Failures: 0, Errors: 0, Time elapsed: 1.551 sec
------------- Standard Output ---------------
ERROR - GraphElement.executeAction(292) | action threw exception: A RunTimeException error has occurred
java.lang.RuntimeException: A RunTimeException error has occurred
	at com.sample.action.MessageActionHandlerExc2.execute(MessageActionHandlerExc2.java:22)
	at org.jbpm.graph.def.Action.execute(Action.java:125)
	at org.jbpm.graph.def.GraphElement.executeAction(GraphElement.java:281)
	at org.jbpm.graph.def.GraphElement.executeActions(GraphElement.java:238)
	at org.jbpm.graph.def.GraphElement.fireAndPropagateEvent(GraphElement.java:212)
	at org.jbpm.graph.def.GraphElement.fireEvent(GraphElement.java:195)
	at org.jbpm.graph.def.Transition.take(Transition.java:151)
	at org.jbpm.graph.def.Node.leave(Node.java:477)
	at org.jbpm.graph.node.StartState.leave(StartState.java:80)
	at org.jbpm.graph.exe.Token.signal(Token.java:226)
	at org.jbpm.graph.exe.Token.signal(Token.java:149)
	at org.jbpm.graph.exe.ProcessInstance.signal(ProcessInstance.java:304)
	at com.sample.ExceptionProcessTest.testExceptionProcess(ExceptionProcessTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:79)
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:420)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:911)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:768)
Inside RuntimeExceptionAction
ERROR - GraphElement.executeAction(292) | action threw exception: An Exception error has occurred
java.text.ParseException: An Exception error has occurred
	at com.sample.action.MessageActionHandlerExc.execute(MessageActionHandlerExc.java:25)
	at org.jbpm.graph.def.Action.execute(Action.java:125)
	at org.jbpm.graph.def.GraphElement.executeAction(GraphElement.java:281)
	at org.jbpm.graph.def.GraphElement.executeActions(GraphElement.java:238)
	at org.jbpm.graph.def.GraphElement.fireAndPropagateEvent(GraphElement.java:212)
	at org.jbpm.graph.def.GraphElement.fireEvent(GraphElement.java:195)
	at org.jbpm.graph.def.Transition.take(Transition.java:151)
	at org.jbpm.graph.def.Node.leave(Node.java:477)
	at org.jbpm.graph.exe.Token.signal(Token.java:226)
	at org.jbpm.graph.exe.Token.signal(Token.java:149)
	at org.jbpm.graph.exe.ProcessInstance.signal(ProcessInstance.java:304)
	at com.sample.ExceptionProcessTest.testExceptionProcess(ExceptionProcessTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:79)
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:420)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:911)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:768)
Inside ParseExceptionAction
ERROR - GraphElement.executeAction(292) | action threw exception: GeneralSecurityException
java.security.GeneralSecurityException: GeneralSecurityException
	at com.sample.action.MessageActionHandlerExc3.execute(MessageActionHandlerExc3.java:24)
	at org.jbpm.graph.def.Action.execute(Action.java:125)
	at org.jbpm.graph.def.GraphElement.executeAction(GraphElement.java:281)
	at org.jbpm.graph.def.GraphElement.executeActions(GraphElement.java:238)
	at org.jbpm.graph.def.GraphElement.fireAndPropagateEvent(GraphElement.java:212)
	at org.jbpm.graph.def.GraphElement.fireEvent(GraphElement.java:195)
	at org.jbpm.graph.def.Transition.take(Transition.java:151)
	at org.jbpm.graph.def.Node.leave(Node.java:477)
	at org.jbpm.graph.exe.Token.signal(Token.java:226)
	at org.jbpm.graph.exe.Token.signal(Token.java:149)
	at org.jbpm.graph.exe.ProcessInstance.signal(ProcessInstance.java:304)
	at com.sample.ExceptionProcessTest.testExceptionProcess(ExceptionProcessTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:79)
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:420)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:911)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:768)
Inside ExceptionAction: GeneralSecurityException
*** ENTERED NODE notify-of-error ***
------------- ---------------- ---------------

Testcase: testExceptionProcess took 1.537 sec
